[versions]
agp = "8.5.2"
daily-android-client = "0.27.0"
kotlin = "2.0.20"
coreKtx = "1.13.1"
kotlinxCoroutinesTest = "1.8.1"
kotlinxSerializationJson = "1.7.1"
kotlinxSerializationPlugin = "2.0.20"
dokka = "1.9.20"
androidxTest = "1.6.1"
okhttp = "4.12.0"
pipecatClient = "0.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
daily-android-client = { module = "co.daily:client", version.ref = "daily-android-client" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
pipecat-client = { module = "ai.pipecat:client", version.ref = "pipecatClient" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerializationPlugin" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
